modLoader="javafml" #mandatory
loaderVersion="[33,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="eo2" #mandatory
version="1.16.2-1.0.0" #mandatory
displayName="Extra Ores" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="" #optional
authors="CraigoryOfAshdale" #optional
description='''
Adds more ores to the game!

'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[33,)" #mandatory

    ordering="NONE"

    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
